
live_config_reload = true

[env]
term = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"

opacity = 0.7
blur = true

title = "Alacritty"

padding = { x = 0, y = 0 }
dynamic_padding = true

decorations = "Buttonless"
decorations_theme_variant = "Dark"

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 15.0

[scrolling]
history = 5000
multiplier = 3

[mouse]
hide_when_typing = true

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'

